import type { Testimonial } from "@/components/WhatsAppTestimonials";

export const criminalTestimonials: Testimonial[] = [
  {
    id: 1,
    clientName: "Família R.",
    clientInitials: "FR",
    avatarUrl: "https://randomuser.me/api/portraits/men/52.jpg",
    area: "Audiência de Custódia",
    date: "HOJE",
    batteryLevel: 84,
    statusBarTime: "07:42",
    messages: [
      {
        type: "sent",
        text: "Liberdade provisória deferida na audiência de custódia. Ele já está saindo. ⚖️",
        time: "07:35",
        seen: true,
      },
      {
        type: "received",
        text: "Doutor, não acredito... A gente passou a noite toda sem dormir... 😭",
        time: "07:38",
        reaction: "🙏",
      },
      {
        type: "received",
        text: "Como agradecer? Vocês foram pra delegacia 3h da manhã!",
        time: "07:39",
      },
      {
        type: "sent",
        text: "É o nosso trabalho. Agora vamos preparar a defesa com calma.",
        time: "07:42",
        seen: true,
      },
    ],
  },
  {
    id: 2,
    clientName: "Daniel M.",
    clientInitials: "DM",
    avatarUrl: "https://randomuser.me/api/portraits/men/41.jpg",
    area: "Habeas Corpus",
    date: "ONTEM",
    batteryLevel: 71,
    statusBarTime: "15:18",
    messages: [
      {
        type: "sent",
        text: "Daniel, o STJ concedeu a ordem. Habeas corpus deferido. 🎯",
        time: "15:10",
        seen: true,
        reaction: "💪",
      },
      {
        type: "received",
        text: "Doutor... eu estava perdendo a esperança. Sério.",
        time: "15:14",
      },
      {
        type: "audio",
        duration: "0:52",
        time: "15:16",
      },
      {
        type: "sent",
        text: "A tese de excesso de prazo foi acolhida. Documentação chegou no domicílio amanhã.",
        time: "15:18",
        seen: true,
      },
    ],
    audioTranscript:
      "Doutor, eu nem sei o que falar. Vocês acreditaram na minha defesa quando ninguém mais acreditava. Obrigado por cada peça, por cada audiência.",
  },
  {
    id: 3,
    clientName: "Marcelo S.",
    clientInitials: "MS",
    avatarUrl: "https://randomuser.me/api/portraits/men/63.jpg",
    area: "Tribunal do Júri",
    date: "12/05/2026",
    batteryLevel: 92,
    statusBarTime: "21:14",
    messages: [
      {
        type: "sent",
        text: "Absolvição. Por 5 votos a 2 no Plenário. 🙏",
        time: "21:06",
        seen: true,
      },
      {
        type: "received",
        text: "DOUTOR!! Não consigo nem digitar direito de tanto chorar... 😭😭",
        time: "21:09",
        reaction: "❤️",
      },
      {
        type: "received",
        text: "Três dias de Plenário. Vocês não dormiram. Minha família inteira tá em silêncio aqui.",
        time: "21:11",
      },
      {
        type: "sent",
        text: "Foi mérito da sua história Marcelo. Nós só ajudamos a contá-la.",
        time: "21:14",
        seen: true,
      },
    ],
  },
  {
    id: 4,
    clientName: "Família L.",
    clientInitials: "FL",
    avatarUrl: "https://randomuser.me/api/portraits/women/48.jpg",
    area: "Execução Penal",
    date: "ONTEM",
    batteryLevel: 58,
    statusBarTime: "10:33",
    messages: [
      {
        type: "sent",
        text: "Progressão deferida. Ele passa pro semiaberto na próxima semana. 🔑",
        time: "10:25",
        seen: true,
        reaction: "🙏",
      },
      {
        type: "received",
        text: "Doutor, depois de 4 anos... 😭",
        time: "10:30",
      },
      {
        type: "received",
        text: "Ele vai poder ver a filha crescer agora.",
        time: "10:31",
      },
      {
        type: "sent",
        text: "Próximo passo é o livramento. Já vamos preparando.",
        time: "10:33",
        seen: true,
      },
    ],
  },
  {
    id: 5,
    clientName: "Ricardo T.",
    clientInitials: "RT",
    avatarUrl: "https://randomuser.me/api/portraits/men/27.jpg",
    area: "Trancamento de Ação Penal",
    date: "HOJE",
    batteryLevel: 67,
    statusBarTime: "11:45",
    messages: [
      {
        type: "sent",
        text: "Tribunal trancou a ação penal. Acolheram a ausência de justa causa. ⚖️",
        time: "11:38",
        seen: true,
      },
      {
        type: "received",
        text: "Vocês desmontaram a denúncia inteira... a investigação não tinha fundamento!",
        time: "11:42",
      },
      {
        type: "received",
        text: "Era pra eu responder a processo por dois anos. Acabou em três meses.",
        time: "11:43",
        reaction: "💪",
      },
      {
        type: "sent",
        text: "Leitura dos autos faz diferença. Sempre.",
        time: "11:45",
        seen: true,
      },
    ],
  },
  {
    id: 6,
    clientName: "Patrícia C.",
    clientInitials: "PC",
    avatarUrl: "https://randomuser.me/api/portraits/women/61.jpg",
    area: "Medida Protetiva",
    date: "08/05/2026",
    batteryLevel: 79,
    statusBarTime: "18:22",
    messages: [
      {
        type: "sent",
        text: "Medida protetiva concedida. Ele não pode mais se aproximar de você ou das crianças.",
        time: "18:15",
        seen: true,
      },
      {
        type: "received",
        text: "Doutora... eu posso voltar pra casa? Posso dormir sem medo hoje?",
        time: "18:19",
        reaction: "❤️",
      },
      {
        type: "sent",
        text: "Pode. E qualquer descumprimento, você liga direto pra mim. A qualquer hora.",
        time: "18:21",
        seen: true,
      },
      {
        type: "received",
        text: "Obrigada por me ouvir quando ninguém mais ouvia. 🙏",
        time: "18:22",
      },
    ],
  },
];
